#!/bin/bash

source .secrets

export PORT=$PORT
export IP=$IP
export BASE_URL="$BASE_URL"

export AI_LIBRARY_URL="$AI_LIBRARY_URL"
export AI_LIBRARY_USERNAME="$AI_LIBRARY_USERNAME"
export AI_LIBRARY_PASSWORD="$AI_LIBRARY_PASSWORD"

export S3_ENDPOINT="$S3_ENDPOINT"
export S3_BUCKET="$S3_BUCKET"
export S3_PREFIX="$S3_PREFIX"
export S3_ACCESS_KEY_ID="$S3_ACCESS_KEY_ID"
export S3_SECRET_ACCESS_KEY="$S3_SECRET_ACCESS_KEY"

export ACTIVATIONS_URL="$ACTIVATIONS_URL"

npm run dev